// Generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id YOUR_ID > types/database.ts
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]
