// Generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id YOUR_ID > types/database.ts
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

/**
 * Tipo manual para app_settings hasta que se generen los tipos completos con Supabase CLI.
 * Cuando se ejecute `supabase gen types`, reemplazar esto con el output generado.
 */
export interface AppSettingsDatabase {
  public: {
    Tables: {
      app_settings: {
        Row: { key: string; value: Json; updated_at: string }
        Insert: { key: string; value: Json; updated_at?: string }
        Update: { key?: string; value?: Json; updated_at?: string }
        Relationships: []
      }
    }
    Views: { [key: string]: never }
    Functions: { [key: string]: never }
    Enums: { [key: string]: never }
    CompositeTypes: { [key: string]: never }
  }
}
